### PR TITLE
[SC] State.Clear fix

### LINKED ISSUE #594: [SC] State.Clear doesn't work correctly
When `State.Clear` is called it pushes null to the cache. If nothing attempts to read the value before the transaction is executed, the cache value is pushed to storage and everything is fine. However if the value is read before execution is completed, the value in the cache won't have been cleared.

### PR DESCRIPTION
**Pull request by rowandh**
Closes #594.

Of the [currently deployed mainnet contracts](https://github.com/stratisproject/CirrusSmartContracts/tree/master/Mainnet):
* AddressMapper uses clear but doesn't attempt to read the value after clearing and is unaffected
* DaoContract doesn't use clear
* IdentityProvider uses clear but is unaffected
* PrivateYesNoVote doesn't use clear
* StandardToken doesn't use clear

[Testnet](https://github.com/stratisproject/CirrusSmartContracts/tree/master/Testnet):
* Airdrop unaffected
* ICOContract **affected**, currently syncing testnet to check if there will be consensus issues
* StratisSwap unaffected
* TicketBooth unaffected
* WheelGame unaffected

### CODE REVIEW

**Comment by rowandh** [comment]
I was able to sync both testnet and mainnet

File: src/Stratis.SmartContracts.IntegrationTests/SmartContracts/ClearDataContract.cs [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+    }
+
+    public bool Check()
+    {
+        Assert(Serializer.ToString(this.Data) != "Test", "Value is still test!");
+
+        return this.Data.Length == 0;
+    }
+
+    public void SetData(string data)
```
Comment (YakupIpek) [inline src/Stratis.SmartContracts.IntegrationTests/SmartContracts/ClearDataContract.cs:42]: Are these necessary to have ? Already Data property has getter and setters.

**Review by YakupIpek — APPROVED** [review]
I tested it on my local chain and it works.

**Review by fassadlr — APPROVED** [review]
